### ISSUE TITLE
use dynamic imports

### ISSUE THREAD

**Issue by heyk1n** [heyk1n/Nita-V1#13]

**Comment by 4wre** [comment]
LHO?? bknnya pke manifest lebih bagus?

**Comment by heyk1n** [comment]
> LHO?? bknnya pke manifest lebih bagus?

Klo gue pikir-pikir lagi ya lebih efektif manifest sih, kalo pake dynamic impor malah baca directory berulang kali wkwkwk, gue close dah OWAOOWKWOWK
